version: '3'

services:
  app:
    build: .
    ports:
      - "192.168.1.155:3002:3002"
    volumes:
      - ./src:/app/src
    command: npm run dev
  nginx:
    image: nginx:alpine
    ports:
      - "192.168.1.155:3004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app

networks:
  app-network:
    driver: bridge 